name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install choco
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    
    - name: Install Git
      shell: pwsh
      run: choco install git
    
    - name: Install msys2
      shell: pwsh
      run: choco install msys2
    
#     - name: Install visualstudio2022
#       shell: pwsh
#       run: choco install visualstudio2022-workload-vctools
    
    - name: Install pipx and gvsbuild
      shell: pwsh
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install gvsbuild
        
    - name: Build GTK
      shell: pwsh
      run: gvsbuild build gtk4 --clean

